spring:
  rabbitmq:
    host: 175.178.29.193
    port: 5672
    username: root
    password: an4869
    publisher-returns: true
    publisher-confirm-type: CORRELATED
    listener:
      type: direct
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
    template:
      retry:
        enabled: true
  kafka:
    bootstrap-servers:
      - 175.178.29.193:19092
      - 175.178.29.193:29092
      - 175.178.29.193:39092
    producer:
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers:
        - 175.178.29.193:19092
        - 175.178.29.193:29092
        - 175.178.29.193:39092
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test
      auto-offset-reset: latest
rocketmq:
  name-server: 175.178.29.193:9876
  producer:
    group: orderProducerGroup
  consumer:
    group: orderTopic_shop_goods
    topic: orderTopic